//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talegen.Common.Messaging.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Talegen.Common.Messaging.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified folder &quot;{0}&quot; for email message templates was not found..
        /// </summary>
        internal static string EmailTemplateDirectoryNotFoundErrorText {
            get {
                return ResourceManager.GetString("EmailTemplateDirectoryNotFoundErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed Hosted Message Queue Job is running..
        /// </summary>
        internal static string LoggingBackgroundJobRunningText {
            get {
                return ResourceManager.GetString("LoggingBackgroundJobRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed Hosted Message Queue Job is stopping..
        /// </summary>
        internal static string LoggingBackgroundJobStoppingText {
            get {
                return ResourceManager.GetString("LoggingBackgroundJobStoppingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve message from queue successfully during StoreQueue()..
        /// </summary>
        internal static string LoggingErrorQueueLoadText {
            get {
                return ResourceManager.GetString("LoggingErrorQueueLoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Background Messaging Service. Type: {0}.
        /// </summary>
        internal static string LoggingProcessingBackgroundJobText {
            get {
                return ResourceManager.GetString("LoggingProcessingBackgroundJobText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred within the message sender job service..
        /// </summary>
        internal static string MessageSenderErrorText {
            get {
                return ResourceManager.GetString("MessageSenderErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} must have a value..
        /// </summary>
        internal static string ParameterMustBeSpecifiedText {
            get {
                return ResourceManager.GetString("ParameterMustBeSpecifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the SendGrid processor execution..
        /// </summary>
        internal static string ProcessorSendGridErrorText {
            get {
                return ResourceManager.GetString("ProcessorSendGridErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the SMTP processor execution..
        /// </summary>
        internal static string ProcessorSmtpErrorText {
            get {
                return ResourceManager.GetString("ProcessorSmtpErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to store queued messages to directory &quot;{0}&quot;..
        /// </summary>
        internal static string StorageDirectoryCommandErrorText {
            get {
                return ResourceManager.GetString("StorageDirectoryCommandErrorText", resourceCulture);
            }
        }
    }
}
